//
//  LocationLoader.swift
//  WildTales
//
//  Created by Kurt McCullough on 19/4/2025.
//

// help to load the locations from locations.json that stores all the locatons on device
//
// Lots of pre-exisitng map pins to add from here as loading them from a stadard JSON in the xcode file was providing lots of errors

import CoreLocation
import Foundation

class LocationLoader {
    static let fileName = "locations.json"  // create a file to store locations

    // A lot of these entries were generated by ChatGPT with the prompt "Create a few more of these for around brisbane"and pasting a example location
    // Ones for UQ have been generated by the WildTales Team
    // These are all defaults loaded with the application, creating a custom pin will add more.
    static let defaultLocations: [Location] = [
        // Southbank Parklands
        Location(
            id: UUID(),
            name: "Southbank Rainforest Walk",
            description:
                "Explore a lush subtropical rainforest in the heart of the city.",
            latitude: -27.4810,
            longitude: 153.0234,
            visited: 0,
            quizQuestion: "What type of forest is found here?",
            quizAnswers: ["Temperate", "Tropical", "Subtropical", "Boreal"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .plant,
            zone: "Southbank Parklands"
        ),
        Location(
            id: UUID(),
            name: "Streets Beach",
            description: "A man-made beach along the Brisbane River.",
            latitude: -27.4796,
            longitude: 153.0235,
            visited: 0,
            quizQuestion: "What is unique about this beach?",
            quizAnswers: ["Saltwater", "Artificial", "Natural", "Tidal"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "Southbank Parklands"
        ),
        Location(
            id: UUID(),
            name: "Nepalese Pagoda",
            description: "A hand-carved monument gifted from Nepal.",
            latitude: -27.4791,
            longitude: 153.0231,
            visited: 0,
            quizQuestion: "Which country gifted this pagoda?",
            quizAnswers: ["India", "China", "Nepal", "Thailand"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "Southbank Parklands"
        ),
        Location(
            id: UUID(),
            name: "Epicurious Garden",
            description: "An edible community garden.",
            latitude: -27.4802,
            longitude: 153.0242,
            visited: 0,
            quizQuestion: "What can you do here?",
            quizAnswers: ["Swim", "Camp", "Pick herbs", "Ride a boat"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .plant,
            zone: "Southbank Parklands"
        ),
        Location(
            id: UUID(),
            name: "Southbank Piazza",
            description: "A venue for live events and performances.",
            latitude: -27.4806,
            longitude: 153.0225,
            visited: 0,
            quizQuestion: "What happens here?",
            quizAnswers: ["Fishing", "Events", "Birdwatching", "Swimming"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "Southbank Parklands"
        ),
        Location(
            id: UUID(),
            name: "Wheel of Brisbane",
            description: "A large observation wheel with city views.",
            latitude: -27.4769,
            longitude: 153.0219,
            visited: 0,
            quizQuestion: "What can you see from the top?",
            quizAnswers: [
                "Mountains", "Brisbane City", "Sydney Opera House", "Desert",
            ],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "Southbank Parklands"
        ),
        Location(
            id: UUID(),
            name: "Arbour Walkway",
            description: "A floral pathway covered in bougainvillea.",
            latitude: -27.4783,
            longitude: 153.0230,
            visited: 0,
            quizQuestion: "Which flower covers the Arbour?",
            quizAnswers: ["Rose", "Bougainvillea", "Lavender", "Sunflower"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .plant,
            zone: "Southbank Parklands"
        ),
        Location(
            id: UUID(),
            name: "Riverside Green",
            description: "Open grassy space for play and events.",
            latitude: -27.4787,
            longitude: 153.0237,
            visited: 0,
            quizQuestion: "What is Riverside Green used for?",
            quizAnswers: [
                "Camping", "Swimming", "Events and picnics", "Shopping",
            ],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "Southbank Parklands"
        ),
        Location(
            id: UUID(),
            name: "Southbank Playgrounds",
            description: "A fun play area for children.",
            latitude: -27.4794,
            longitude: 153.0241,
            visited: 0,
            quizQuestion: "Who uses this area the most?",
            quizAnswers: ["Adults", "Birds", "Children", "Cyclists"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "Southbank Parklands"
        ),
        Location(
            id: UUID(),
            name: "Rainforest Amphitheatre",
            description: "Hidden stage surrounded by nature.",
            latitude: -27.4801,
            longitude: 153.0232,
            visited: 0,
            quizQuestion: "What happens at this spot?",
            quizAnswers: ["Weddings", "Swimming", "Performances", "Fishing"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "Southbank Parklands"
        ),

        // University of Queensland
        Location(
            id: UUID(),
            name: "Great Court",
            description: "The iconic sandstone heart of UQ.",
            latitude: -27.4975,
            longitude: 153.0137,
            visited: 0,
            quizQuestion: "What is the Great Court known for?",
            quizAnswers: [
                "Libraries", "Shops", "Sandstone buildings", "Dormitories",
            ],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "University of Queensland"
        ),
        Location(
            id: UUID(),
            name: "UQ Lakes",
            description: "A serene spot for wildlife and walking.",
            latitude: -27.5002,
            longitude: 153.0152,
            visited: 0,
            quizQuestion: "Which animals are common here?",
            quizAnswers: ["Kangaroos", "Ducks", "Koalas", "Emus"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .animal,
            zone: "University of Queensland"
        ),
        Location(
            id: UUID(),
            name: "Biological Sciences Building",
            description: "Home to biology research and classes.",
            latitude: -27.4968,
            longitude: 153.0143,
            visited: 0,
            quizQuestion: "What is studied here?",
            quizAnswers: ["Law", "Biology", "Engineering", "History"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "University of Queensland"
        ),
        Location(
            id: UUID(),
            name: "UQ Art Museum",
            description: "Features contemporary exhibitions.",
            latitude: -27.4963,
            longitude: 153.0129,
            visited: 0,
            quizQuestion: "What is displayed here?",
            quizAnswers: ["Sculptures", "Art", "Cars", "Books"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "University of Queensland"
        ),
        Location(
            id: UUID(),
            name: "Physics Lawn",
            description: "Open grass space used by students.",
            latitude: -27.4972,
            longitude: 153.0148,
            visited: 0,
            quizQuestion: "What is commonly done here?",
            quizAnswers: ["Cooking", "Relaxing", "Swimming", "Climbing"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "University of Queensland"
        ),
        Location(
            id: UUID(),
            name: "Alumni Court",
            description: "A peaceful courtyard near sandstone buildings.",
            latitude: -27.4967,
            longitude: 153.0134,
            visited: 0,
            quizQuestion: "What is this area used for?",
            quizAnswers: ["Experiments", "Relaxation", "Cycling", "Parking"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "University of Queensland"
        ),
        Location(
            id: UUID(),
            name: "Central Library",
            description: "Main study and research library.",
            latitude: -27.4970,
            longitude: 153.0130,
            visited: 0,
            quizQuestion: "What can students do here?",
            quizAnswers: ["Cook", "Sleep", "Study", "Dance"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "University of Queensland"
        ),
        Location(
            id: UUID(),
            name: "UQ Union Complex",
            description: "Food, shops, and services for students.",
            latitude: -27.4973,
            longitude: 153.0138,
            visited: 0,
            quizQuestion: "What do students find here?",
            quizAnswers: ["Animals", "Food and shops", "Labs", "Classrooms"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "University of Queensland"
        ),
        Location(
            id: UUID(),
            name: "Forgan Smith Building",
            description: "Iconic sandstone law building.",
            latitude: -27.4960,
            longitude: 153.0135,
            visited: 0,
            quizQuestion: "What subject is taught here?",
            quizAnswers: ["Engineering", "Biology", "Law", "Music"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "University of Queensland"
        ),
        Location(
            id: UUID(),
            name: "UQ Art Sculpture Trail",
            description: "Modern sculptures across campus.",
            latitude: -27.4959,
            longitude: 153.0142,
            visited: 0,
            quizQuestion: "What is displayed here?",
            quizAnswers: ["Graffiti", "Sculptures", "TVs", "Cars"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "University of Queensland"
        ),

        // Botanical Gardens (Mt Coot-tha)
        Location(
            id: UUID(),
            name: "Tropical Dome",
            description: "A climate-controlled greenhouse for exotic plants.",
            latitude: -27.4757,
            longitude: 152.9743,
            visited: 0,
            quizQuestion: "What grows inside the dome?",
            quizAnswers: ["Cacti", "Tropical plants", "Grasses", "Bamboo"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .plant,
            zone: "Botanical Gardens"
        ),
        Location(
            id: UUID(),
            name: "Japanese Garden",
            description: "A peaceful landscape garden gifted by Japan.",
            latitude: -27.4762,
            longitude: 152.9751,
            visited: 0,
            quizQuestion: "Who gifted this garden?",
            quizAnswers: ["Korea", "Japan", "China", "Vietnam"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .plant,
            zone: "Botanical Gardens"
        ),
        Location(
            id: UUID(),
            name: "Bonsai House",
            description: "Exhibits miniature potted trees.",
            latitude: -27.4759,
            longitude: 152.9738,
            visited: 0,
            quizQuestion: "What is displayed here?",
            quizAnswers: [
                "Palm trees", "Flowers", "Bonsai trees", "Succulents",
            ],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .plant,
            zone: "Botanical Gardens"
        ),
        Location(
            id: UUID(),
            name: "Fern House",
            description: "A collection of native and exotic ferns.",
            latitude: -27.4764,
            longitude: 152.9746,
            visited: 0,
            quizQuestion: "What type of plant is featured?",
            quizAnswers: ["Ferns", "Cacti", "Mosses", "Flowers"],
            correctAnswerIndex: 0,
            quizCompleted: false,
            category: .plant,
            zone: "Botanical Gardens"
        ),
        Location(
            id: UUID(),
            name: "Lagoon",
            description: "Water habitat surrounded by lush vegetation.",
            latitude: -27.4753,
            longitude: 152.9754,
            visited: 0,
            quizQuestion: "What can be seen here?",
            quizAnswers: [
                "Desert plants", "Water lilies", "Sand dunes", "Algae tanks",
            ],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .plant,
            zone: "Botanical Gardens"
        ),
        Location(
            id: UUID(),
            name: "Native Plant Section",
            description: "Collection of Australian native species.",
            latitude: -27.4752,
            longitude: 152.9748,
            visited: 0,
            quizQuestion: "Which plant type is featured?",
            quizAnswers: ["Foreign", "Native", "Cactus", "Seaweed"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .plant,
            zone: "Botanical Gardens"
        ),
        Location(
            id: UUID(),
            name: "Children’s Trail",
            description: "Interactive nature walk for young visitors.",
            latitude: -27.4756,
            longitude: 152.9759,
            visited: 0,
            quizQuestion: "Who is this trail for?",
            quizAnswers: ["Birds", "Students", "Children", "Researchers"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "Botanical Gardens"
        ),
        Location(
            id: UUID(),
            name: "Cactus Garden",
            description: "Succulents and cacti from around the world.",
            latitude: -27.4760,
            longitude: 152.9762,
            visited: 0,
            quizQuestion: "Which plants are here?",
            quizAnswers: ["Ferns", "Cacti", "Trees", "Flowers"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .plant,
            zone: "Botanical Gardens"
        ),
        Location(
            id: UUID(),
            name: "Fragrant Plant Walk",
            description: "Aromatic plants line this peaceful path.",
            latitude: -27.4765,
            longitude: 152.9749,
            visited: 0,
            quizQuestion: "What is special about these plants?",
            quizAnswers: ["Color", "Smell", "Size", "Height"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .plant,
            zone: "Botanical Gardens"
        ),
        Location(
            id: UUID(),
            name: "Lookout Trail Start",
            description: "Entry to trail leading up to scenic views.",
            latitude: -27.4770,
            longitude: 152.9755,
            visited: 0,
            quizQuestion: "Where does this trail lead?",
            quizAnswers: ["Shopping mall", "Cave", "Lookout", "Farm"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "Botanical Gardens"
        ),
        Location(
            id: UUID(),
            name: "UQ Student Union",
            description: "Lots of food to eat here and stores to explore.",
            latitude: -27.497448,
            longitude: 153.015526,
            visited: 0,
            quizQuestion: "What bubble tea place is here?",
            quizAnswers: ["YummyTea", "Chatime", "McDonalds", "Tea4Me"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "University of Queensland"
        ),
        Location(
            id: UUID(),
            name: "UQ Lakes Amphitheater",
            description: "Nice place to sit down and enjoy the sunshine!",
            latitude: -27.498212,
            longitude: 153.015106,
            visited: 0,
            quizQuestion: "What colour is the cover for the stage?",
            quizAnswers: ["Brown", "Yellow", "Green", "Bronze"],
            correctAnswerIndex: 4,
            quizCompleted: false,
            category: .location,
            zone: "University of Queensland"
        ),
        Location(
            id: UUID(),
            name: "Turtles",
            description: "Turtles have been spotted here. Can you see one?",
            latitude: -27.498689,
            longitude: 153.016662,
            visited: 0,
            quizQuestion: "What texture is a turtles shell?",
            quizAnswers: ["Soft", "Hard", "Bubbly", "Jiggly"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .animal,
            zone: "University of Queensland"
        ),
        Location(
            id: UUID(),
            name: "Philantropy Trail Sign",
            description: "A few nice spots to visit around UQ in a trail!",
            latitude: -27.498847,
            longitude: 153.016901,
            visited: 0,
            quizQuestion: "What is the name of the memorial garden here?",
            quizAnswers: ["Charles Darwin", "Stephen Hawking", "Una Prentice", "The green"],
            correctAnswerIndex: 3,
            quizCompleted: false,
            category: .location,
            zone: "University of Queensland"
        ),
        Location(
            id: UUID(),
            name: "Australasian Swamphen",
            description: "Small bird with a red beak, also known as a water hen.",
            latitude: -27.498738,
            longitude: 153.016089,
            visited: 0,
            quizQuestion: "What colour is the beak of the bird?",
            quizAnswers: ["Black", "Brown", "Green", "Red"],
            correctAnswerIndex: 4,
            quizCompleted: false,
            category: .animal,
            zone: "University of Queensland"
        ),
        
        Location(
            id: UUID(),
            name: "UQ Lakes",
            description: "Large bodies of water where lots of animals can be seen.",
            latitude: -27.499454,
            longitude: 153.016019,
            visited: 0,
            quizQuestion: "What is the chemical element for water?",
            quizAnswers: ["H20", "Oxygen", "Aqua", "Water"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "University of Queensland"
        ),
        
        Location(
            id: UUID(),
            name: "Ducks",
            description: "Lots of ducks have been spotted here. Can you see any?.",
            latitude: -27.500718,
            longitude: 153.015787,
            visited: 0,
            quizQuestion: "What kind of animal are ducks?",
            quizAnswers: ["Bird", "Reptile", "Amphibian", "Snake"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .animal,
            zone: "University of Queensland"
        ),
        
        Location(
            id: UUID(),
            name: "Melaleuca Quinquenervia",
            description: "Also known as paper bark trees. There bark is very paper like in texture.",
            latitude: -27.500732,
            longitude: 153.015218,
            visited: 0,
            quizQuestion: "What colour is the bark?",
            quizAnswers: ["Brown", "Dark Green", "Beige", "White"],
            correctAnswerIndex: 3,
            quizCompleted: false,
            category: .plant,
            zone: "University of Queensland"
        ),
        
        Location(
            id: UUID(),
            name: "General Purpose South Building",
            description: "A place for students of UQ to study and collaborate.",
            latitude: -27.499961,
            longitude: 153.014692,
            visited: 0,
            quizQuestion: "What is behind the building?",
            quizAnswers: ["Lakes", "Bridge", "Bus Stop", "Chicken Coop"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "University of Queensland"
        ),
        
        Location(
            id: UUID(),
            name: "Axon Building",
            description: "A place for students of UQ to study and collaborate.",
            latitude: -27.500042,
            longitude: 153.014655,
            visited: 0,
            quizQuestion: "What is the building made of?",
            quizAnswers: ["Steel", "Bricks", "Tin", "Glass"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "University of Queensland"
        ),
        
        Location(
            id: UUID(),
            name: "Sir James Foot Building",
            description: "A place for students of UQ to study and collaborate.",
            latitude: -27.500220,
            longitude: 153.014363,
            visited: 0,
            quizQuestion: "How many stories is this building?",
            quizAnswers: ["1", "2", "3", "4"],
            correctAnswerIndex: 4,
            quizCompleted: false,
            category: .location,
            zone: "University of Queensland"
        ),
        
        Location(
            id: UUID(),
            name: "Euphorbia Milii",
            description: "Also known as the crown of thorns. A small spikey plant with lots of little flowers over it.",
            latitude: -27.499931,
            longitude: 153.014549,
            visited: 0,
            quizQuestion: "What colour are the flowers?",
            quizAnswers: ["Pink", "Blue", "Yellow", "Gren"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .plant,
            zone: "University of Queensland"
        ),
        Location(
            id: UUID(),
            name: "Boeing Research Center",
            description: "A place for research and innovation for Boeing in UQ.",
            latitude: -27.499866,
            longitude: 153.014150,
            visited: 0,
            quizQuestion: "What does Boeing genereally make?",
            quizAnswers: ["Trucks", "Cars", "Boats", "Planes"],
            correctAnswerIndex: 4,
            quizCompleted: false,
            category: .location,
            zone: "University of Queensland"
        ),
        Location(
            id: UUID(),
            name: "Hawkin Engiinering Building",
            description: "Home of engineering and sciences students and for popular research labs such as Boeing. ",
            latitude: -27.499647,
            longitude: 153.013373,
            visited: 0,
            quizQuestion: "What is the library in this building called?",
            quizAnswers: ["Central Library", "Law Library", "Dorothy Hill Library", "Kenmore Library"],
            correctAnswerIndex: 3,
            quizCompleted: false,
            category: .location,
            zone: "University of Queensland"
        ),
        Location(
            id: UUID(),
            name: "Andrew N. Liveris Building",
            description: "University's internationally regarded School of Chemical Engineering ",
            latitude: -27.499237,
            longitude: 153.013392,
            visited: 0,
            quizQuestion: "What colour is the building?",
            quizAnswers: ["Green & Purple", "White & Gold", "Blue & Black", "Green & Gold"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "University of Queensland"
        ),
        Location(
            id: UUID(),
            name: "Jacaranda Mimosifolia",
            description: "Highly regarded as a jacaranda tree. Lots can be found here. ",
            latitude: -27.498576,
            longitude: 153.014009,
            visited: 0,
            quizQuestion: "What colour flowers do these trees produce?",
            quizAnswers: ["Purple", "Gold", "Black", "Green"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .plant,
            zone: "University of Queensland"
        ),
        
        Location(
            id: UUID(),
            name: "Ibis",
            description: "Lots of ibis birds can be found here.",
            latitude: -27.500844,
            longitude: 153.013499,
            visited: 0,
            quizQuestion: "What is the Australian slang for an ibis?",
            quizAnswers: ["Silly Goose", "White Duck", "Bin Bird", "Bin Chicken"],
            correctAnswerIndex: 4,
            quizCompleted: false,
            category: .animal,
            zone: "University of Queensland"
        ),
        
        Location(
            id: UUID(),
            name: "Eucalyptus",
            description: "A native tree to Australia, commonly assosiated with Koalas.",
            latitude: -27.498289,
            longitude: 153.015530,
            visited: 0,
            quizQuestion: "Where are Eucalyptus trees native to?",
            quizAnswers: ["California", "New Zealand", "Australia", "South America"],
            correctAnswerIndex: 3,
            quizCompleted: false,
            category: .plant,
            zone: "University of Queensland"
        ),
        Location(
            id: UUID(),
            name: "Fern",
            description: "Green plants often found in rainforest vegetation.",
            latitude: -27.498033,
            longitude: 153.015937,
            visited: 0,
            quizQuestion: "What countries national plant is a fern?",
            quizAnswers: ["California", "New Zealand", "Australia", "South America"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .plant,
            zone: "University of Queensland"
        ),
        
        Location(
            id: UUID(),
            name: "Zelman Cowen Building",
            description: "A place for students of UQ to study and collaborate.",
            latitude: -27.498995,
            longitude: 153.014277,
            visited: 0,
            quizQuestion: "What subjects are taught here?",
            quizAnswers: ["Music & Architechture", "Music & Science", "Science", "History & Science"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "University of Queensland"
        ),
        
        Location(
            id: UUID(),
            name: "UQ Student Central",
            description: "A central place in UQ for help for students.",
            latitude: -27.498677,
            longitude: 153.013596,
            visited: 0,
            quizQuestion: "What does UQ stand for?",
            quizAnswers: ["Uni Qlo", "University of Queensland", "Unique Queen", "Upper Queensland"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "University of Queensland"
        ),
        
        Location(
            id: UUID(),
            name: "Roma Street Parkland",
            description: "A scenic inner-city park with walking paths and gardens.",
            latitude: -27.4626,
            longitude: 153.0200,
            visited: 0,
            quizQuestion: "Which type of garden is Roma Street Parkland known for?",
            quizAnswers: ["Desert Garden", "Tropical Garden", "Japanese Garden", "Rainforest Garden"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "Brisbane City"
        ),

        Location(
            id: UUID(),
            name: "New Farm Park",
            description: "Popular riverside park known for its rose gardens and weekend markets.",
            latitude: -27.4675,
            longitude: 153.0533,
            visited: 0,
            quizQuestion: "What flower is New Farm Park famous for?",
            quizAnswers: ["Tulips", "Roses", "Daisies", "Lilies"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .plant,
            zone: "New Farm"
        ),

        Location(
            id: UUID(),
            name: "Story Bridge",
            description: "Iconic bridge connecting Kangaroo Point and Fortitude Valley.",
            latitude: -27.4595,
            longitude: 153.0353,
            visited: 0,
            quizQuestion: "What does the Story Bridge connect?",
            quizAnswers: ["New Farm and South Bank", "Brisbane and Gold Coast", "Kangaroo Point and Fortitude Valley", "City and Airport"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "Kangaroo Point"
        ),

        Location(
            id: UUID(),
            name: "Brisbane Powerhouse",
            description: "Cultural hub offering contemporary art, theatre, and events.",
            latitude: -27.4679,
            longitude: 153.0562,
            visited: 0,
            quizQuestion: "What was the Brisbane Powerhouse originally used for?",
            quizAnswers: ["Train station", "Factory", "Power station", "Warehouse"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "New Farm"
        ),

        Location(
            id: UUID(),
            name: "Kangaroo Point Cliffs",
            description: "Popular spot for rock climbing with panoramic city views.",
            latitude: -27.4750,
            longitude: 153.0343,
            visited: 0,
            quizQuestion: "What activity are the Kangaroo Point Cliffs most popular for?",
            quizAnswers: ["Swimming", "Rock climbing", "Hiking", "Cycling"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "Kangaroo Point"
        ),

        Location(
            id: UUID(),
            name: "Brisbane City Botanic Gardens",
            description: "Historic gardens on the Brisbane River, great for walks and picnics.",
            latitude: -27.4769,
            longitude: 153.0309,
            visited: 0,
            quizQuestion: "What is unique about the City Botanic Gardens?",
            quizAnswers: ["It is the oldest garden in Brisbane", "It has a theme park", "It’s only open at night", "It has a zoo"],
            correctAnswerIndex: 0,
            quizCompleted: false,
            category: .plant,
            zone: "Brisbane City"
        ),

        Location(
            id: UUID(),
            name: "Howard Smith Wharves",
            description: "Revitalized riverside area with dining and entertainment.",
            latitude: -27.4638,
            longitude: 153.0359,
            visited: 0,
            quizQuestion: "What was the original use of Howard Smith Wharves?",
            quizAnswers: ["Military base", "Shipping and cargo", "Farming site", "Coal mine"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "Fortitude Valley"
        ),

        Location(
            id: UUID(),
            name: "Woolloongabba Antiques Centre",
            description: "Large warehouse filled with antiques and vintage treasures.",
            latitude: -27.4921,
            longitude: 153.0381,
            visited: 0,
            quizQuestion: "What can you find at the Woolloongabba Antiques Centre?",
            quizAnswers: ["Electronics", "Modern Art", "Antiques and vintage items", "Books only"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "Woolloongabba"
        ),

        Location(
            id: UUID(),
            name: "Highgate Hill Park",
            description: "Quiet park with city views, perfect for a relaxing afternoon.",
            latitude: -27.4890,
            longitude: 153.0208,
            visited: 0,
            quizQuestion: "What is a popular feature of Highgate Hill Park?",
            quizAnswers: ["Beach access", "City skyline views", "Mountain biking", "Skiing slopes"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "Highgate Hill"
        ),

        Location(
            id: UUID(),
            name: "Dutton Park Cemetery",
            description: "Historic cemetery with notable burials and heritage value.",
            latitude: -27.4962,
            longitude: 153.0302,
            visited: 0,
            quizQuestion: "What is Dutton Park Cemetery known for?",
            quizAnswers: ["Historic burials", "Botanical research", "Theme park", "Animal sanctuary"],
            correctAnswerIndex: 0,
            quizCompleted: false,
            category: .location,
            zone: "Dutton Park"
        ),
        
        Location(
            id: UUID(),
            name: "Paddington Antique Centre",
            description: "Historic marketplace filled with antiques, collectibles, and vintage treasures.",
            latitude: -27.4575,
            longitude: 152.9998,
            visited: 0,
            quizQuestion: "What type of items is Paddington Antique Centre famous for?",
            quizAnswers: ["Fresh produce", "Sportswear", "Antiques", "Technology gadgets"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "Paddington"
        ),

        Location(
            id: UUID(),
            name: "Musgrave Park",
            description: "Culturally significant park with Aboriginal heritage and community events.",
            latitude: -27.4814,
            longitude: 153.0178,
            visited: 0,
            quizQuestion: "Why is Musgrave Park culturally significant?",
            quizAnswers: ["Aboriginal heritage", "Colonial mansion", "War memorial", "Historic zoo"],
            correctAnswerIndex: 0,
            quizCompleted: false,
            category: .location,
            zone: "West End"
        ),

        Location(
            id: UUID(),
            name: "Wilson Outlook Reserve",
            description: "Small park offering spectacular views of the Story Bridge and city skyline.",
            latitude: -27.4559,
            longitude: 153.0414,
            visited: 0,
            quizQuestion: "What is the key feature of Wilson Outlook Reserve?",
            quizAnswers: ["River ferry terminal", "City views", "Museum", "Skatepark"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "New Farm"
        ),

        Location(
            id: UUID(),
            name: "Victoria Park",
            description: "Large public parkland formerly a golf course, now redeveloped for recreation.",
            latitude: -27.4479,
            longitude: 153.0162,
            visited: 0,
            quizQuestion: "What was Victoria Park previously used as?",
            quizAnswers: ["Theme park", "Golf course", "Shopping mall", "Racing track"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "Herston"
        ),

        Location(
            id: UUID(),
            name: "Fortitude Music Hall",
            description: "A major live music venue located in the heart of Fortitude Valley.",
            latitude: -27.4580,
            longitude: 153.0350,
            visited: 0,
            quizQuestion: "What is the Fortitude Music Hall primarily used for?",
            quizAnswers: ["Conferences", "Sporting events", "Live music", "Dance classes"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "Fortitude Valley"
        ),

        Location(
            id: UUID(),
            name: "Albion Park Raceway",
            description: "Brisbane’s main harness racing and greyhound racing venue.",
            latitude: -27.4325,
            longitude: 153.0420,
            visited: 0,
            quizQuestion: "Which activity is held at Albion Park Raceway?",
            quizAnswers: ["Soccer", "Rugby", "Horse and greyhound racing", "Swimming"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "Albion"
        ),

        Location(
            id: UUID(),
            name: "Brisbane Skatepark",
            description: "Well-known skateboarding destination next to Paddington and Red Hill.",
            latitude: -27.4541,
            longitude: 152.9965,
            visited: 0,
            quizQuestion: "What is Brisbane Skatepark known for?",
            quizAnswers: ["Basketball courts", "Bird watching", "Skateboarding", "Picnicking"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "Red Hill"
        ),

        Location(
            id: UUID(),
            name: "Lutwyche Cemetery",
            description: "A large, historic cemetery with war graves and heritage-listed monuments.",
            latitude: -27.4110,
            longitude: 153.0278,
            visited: 0,
            quizQuestion: "What distinguishes Lutwyche Cemetery?",
            quizAnswers: ["It has a lake", "It hosts concerts", "It has war graves", "It's underground"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "Lutwyche"
        ),

        Location(
            id: UUID(),
            name: "Mowbray Park",
            description: "Park along the Brisbane River with ferry access and scenic spots.",
            latitude: -27.4810,
            longitude: 153.0460,
            visited: 0,
            quizQuestion: "What feature is found at Mowbray Park?",
            quizAnswers: ["Ferry terminal", "Waterfall", "Beach", "Cave system"],
            correctAnswerIndex: 0,
            quizCompleted: false,
            category: .location,
            zone: "East Brisbane"
        ),

        Location(
            id: UUID(),
            name: "Norman Creek",
            description: "Urban creek winding through several suburbs, with walking trails.",
            latitude: -27.4960,
            longitude: 153.0500,
            visited: 0,
            quizQuestion: "What natural feature is Norman Creek?",
            quizAnswers: ["Mountain", "Creek", "Forest", "Volcano"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "Greenslopes"
        ),
        Location(
            id: UUID(),
            name: "Toowong Cemetery",
            description: "One of Brisbane’s oldest cemeteries with historic graves and monuments.",
            latitude: -27.4648,
            longitude: 152.9936,
            visited: 0,
            quizQuestion: "What is Toowong Cemetery best known for?",
            quizAnswers: ["Wildlife sanctuary", "Concerts", "Historic graves", "Botanic collections"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "Toowong"
        ),

        Location(
            id: UUID(),
            name: "Yeronga Memorial Park",
            description: "A heritage-listed park with sports fields and war memorials.",
            latitude: -27.5152,
            longitude: 153.0223,
            visited: 0,
            quizQuestion: "What is commemorated in Yeronga Memorial Park?",
            quizAnswers: ["Explorers", "Soldiers", "Artists", "Athletes"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "Yeronga"
        ),

        Location(
            id: UUID(),
            name: "Bulimba Memorial Park",
            description: "Community park with ANZAC memorials and recreational facilities.",
            latitude: -27.4494,
            longitude: 153.0591,
            visited: 0,
            quizQuestion: "Where is Bulimba Memorial Park located?",
            quizAnswers: ["West End", "Bulimba", "Ashgrove", "Greenslopes"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "Bulimba"
        ),

        Location(
            id: UUID(),
            name: "Ashgrove Library",
            description: "Local library with community programs and historical displays.",
            latitude: -27.4431,
            longitude: 152.9937,
            visited: 0,
            quizQuestion: "What type of facility is Ashgrove Library?",
            quizAnswers: ["Museum", "Library", "Zoo", "Observatory"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "Ashgrove"
        ),

        Location(
            id: UUID(),
            name: "Greenslopes Mall",
            description: "Suburban shopping center with local shops and services.",
            latitude: -27.5101,
            longitude: 153.0455,
            visited: 0,
            quizQuestion: "What can you mainly find at Greenslopes Mall?",
            quizAnswers: ["Amusement rides", "Wild animals", "Retail stores", "Lakes"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "Greenslopes"
        ),

        Location(
            id: UUID(),
            name: "Bowen Hills Railway Station",
            description: "Busy inner-city train station serving multiple lines.",
            latitude: -27.4449,
            longitude: 153.0342,
            visited: 0,
            quizQuestion: "What kind of facility is Bowen Hills?",
            quizAnswers: ["Bus terminal", "Train station", "Helipad", "Ferry port"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "Bowen Hills"
        ),

        Location(
            id: UUID(),
            name: "Nundah Tunnel",
            description: "Underground transport route beneath the Nundah village area.",
            latitude: -27.4023,
            longitude: 153.0627,
            visited: 0,
            quizQuestion: "What is the Nundah Tunnel used for?",
            quizAnswers: ["Cycling", "Road traffic", "Water drainage", "Trams"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "Nundah"
        ),

        Location(
            id: UUID(),
            name: "Griffith University EcoCentre",
            description: "Environmental education and research hub at Griffith's Nathan campus.",
            latitude: -27.5469,
            longitude: 153.0613,
            visited: 0,
            quizQuestion: "What is the EcoCentre at Griffith University focused on?",
            quizAnswers: ["Astronomy", "Marine animals", "Sustainability and environment", "Mining"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .plant,
            zone: "Nathan"
        ),

        Location(
            id: UUID(),
            name: "The Old Windmill",
            description: "Historic convict-era windmill tower in the city.",
            latitude: -27.4651,
            longitude: 153.0241,
            visited: 0,
            quizQuestion: "What was the Old Windmill originally used for?",
            quizAnswers: ["Signal tower", "Lighthouse", "Wind-powered grain grinding", "Watchtower"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "Spring Hill"
        ),

        Location(
            id: UUID(),
            name: "Dornoch Terrace Bridge",
            description: "Heritage-listed bridge linking West End and Highgate Hill.",
            latitude: -27.4816,
            longitude: 153.0120,
            visited: 0,
            quizQuestion: "Dornoch Terrace Bridge connects which suburbs?",
            quizAnswers: ["Kangaroo Point and New Farm", "West End and Highgate Hill", "Ashgrove and Toowong", "Bulimba and South Bank"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "Highgate Hill"
        ),
        
        Location(
            id: UUID(),
            name: "Guyatt Park",
            description: "Riverfront park with a ferry terminal, playground, and open green space.",
            latitude: -27.4932,
            longitude: 153.0037,
            visited: 0,
            quizQuestion: "What public transport is available at Guyatt Park?",
            quizAnswers: ["Train", "Bus", "Ferry", "Tram"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "St Lucia"
        ),

        Location(
            id: UUID(),
            name: "Toowong Village",
            description: "Major shopping and business center next to Toowong railway station.",
            latitude: -27.4828,
            longitude: 152.9933,
            visited: 0,
            quizQuestion: "What type of place is Toowong Village?",
            quizAnswers: ["Theme park", "Shopping center", "Park", "Hospital"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "Toowong"
        ),

        Location(
            id: UUID(),
            name: "Regatta Ferry Terminal",
            description: "Historic riverside ferry stop serving the Toowong area.",
            latitude: -27.4845,
            longitude: 152.9997,
            visited: 0,
            quizQuestion: "Which transport method is associated with the Regatta Terminal?",
            quizAnswers: ["Train", "Ferry", "Cable car", "Bus"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "Toowong"
        ),

        Location(
            id: UUID(),
            name: "Indooroopilly Shopping Centre",
            description: "One of Brisbane's largest retail complexes with over 300 stores.",
            latitude: -27.5030,
            longitude: 152.9745,
            visited: 0,
            quizQuestion: "What is Indooroopilly Shopping Centre known for?",
            quizAnswers: ["Museums", "Retail stores", "Sports grounds", "Animal exhibits"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "Indooroopilly"
        ),

        Location(
            id: UUID(),
            name: "Indooroopilly Library",
            description: "Modern library with a wide range of books, events, and study areas.",
            latitude: -27.5029,
            longitude: 152.9749,
            visited: 0,
            quizQuestion: "Where is the Indooroopilly Library located?",
            quizAnswers: ["Near the river", "At a train station", "In the shopping centre", "Next to a park"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "Indooroopilly"
        ),

        Location(
            id: UUID(),
            name: "Kenmore Village",
            description: "Local shopping area with supermarkets, cafés, and essential services.",
            latitude: -27.5097,
            longitude: 152.9383,
            visited: 0,
            quizQuestion: "What can you find at Kenmore Village?",
            quizAnswers: ["A zoo", "Shopping and services", "Beach access", "Train station"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .location,
            zone: "Kenmore"
        ),

        Location(
            id: UUID(),
            name: "Akuna Oval",
            description: "Large sports and recreation park used by local clubs and families.",
            latitude: -27.5055,
            longitude: 152.9359,
            visited: 0,
            quizQuestion: "Which activity is common at Akuna Oval?",
            quizAnswers: ["Fishing", "Hiking", "Team sports", "Boating"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "Kenmore"
        ),

        Location(
            id: UUID(),
            name: "Brookfield Showgrounds",
            description: "Host of the annual Brookfield Show and various community events.",
            latitude: -27.5020,
            longitude: 152.8893,
            visited: 0,
            quizQuestion: "What event is the Brookfield Showgrounds known for?",
            quizAnswers: ["Music festival", "State fair", "Brookfield Show", "Night markets"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "Brookfield"
        ),

        Location(
            id: UUID(),
            name: "Brookfield General Store",
            description: "Historic shop and café that’s been serving the local community for generations.",
            latitude: -27.5034,
            longitude: 152.8915,
            visited: 0,
            quizQuestion: "What is the Brookfield General Store known for?",
            quizAnswers: ["Local arts", "Pet adoption", "Historic charm and café", "Camping gear"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .location,
            zone: "Brookfield"
        ),

        Location(
            id: UUID(),
            name: "Biami Yumba Park",
            description: "Parkland featuring walking trails and nature-themed playground.",
            latitude: -27.5123,
            longitude: 152.9504,
            visited: 0,
            quizQuestion: "What can you do at Biami Yumba Park?",
            quizAnswers: ["Play sports", "Camp overnight", "Enjoy nature trails and play", "Go shopping"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .plant,
            zone: "Fig Tree Pocket"
        ),
        
        Location(
            id: UUID(),
            name: "Common Brushtail Possum",
            description: "A nocturnal marsupial commonly seen in suburban Brisbane trees.",
            latitude: -27.4705,
            longitude: 153.0260,
            visited: 0,
            quizQuestion: "What time of day is the Common Brushtail Possum most active?",
            quizAnswers: ["Morning", "Afternoon", "Night", "All day"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .animal,
            zone: "Brisbane City"
        ),

        Location(
            id: UUID(),
            name: "Eastern Water Dragon",
            description: "A lizard commonly seen basking along riverbanks and in parks.",
            latitude: -27.4769,
            longitude: 153.0302,
            visited: 0,
            quizQuestion: "What is a unique feature of the Eastern Water Dragon?",
            quizAnswers: ["Can fly", "Swims well", "Has fur", "Makes webs"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .animal,
            zone: "Kangaroo Point"
        ),

        Location(
            id: UUID(),
            name: "Australian Magpie",
            description: "A smart and vocal bird known for its warbling songs and swooping season.",
            latitude: -27.5087,
            longitude: 153.0386,
            visited: 0,
            quizQuestion: "Why do magpies swoop?",
            quizAnswers: ["To scare cats", "To protect their nests", "For fun", "To hunt"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .animal,
            zone: "Greenslopes"
        ),

        Location(
            id: UUID(),
            name: "Laughing Kookaburra",
            description: "A large kingfisher famous for its loud, human-like laugh.",
            latitude: -27.4895,
            longitude: 153.0423,
            visited: 0,
            quizQuestion: "What is the Kookaburra’s laugh used for?",
            quizAnswers: ["Calling for food", "Territory display", "Mating", "Scaring predators"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .animal,
            zone: "Carindale"
        ),

        Location(
            id: UUID(),
            name: "Rainbow Lorikeet",
            description: "A colorful and noisy parrot that feeds on nectar.",
            latitude: -27.4234,
            longitude: 153.0001,
            visited: 0,
            quizQuestion: "What do Rainbow Lorikeets mainly eat?",
            quizAnswers: ["Seeds", "Nectar", "Insects", "Meat"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .animal,
            zone: "The Gap"
        ),

        Location(
            id: UUID(),
            name: "Tawny Frogmouth",
            description: "Often mistaken for an owl, this bird camouflages against tree bark.",
            latitude: -27.4500,
            longitude: 152.9912,
            visited: 0,
            quizQuestion: "What is the Tawny Frogmouth’s best defense?",
            quizAnswers: ["Flying fast", "Sharp beak", "Camouflage", "Loud call"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .animal,
            zone: "Paddington"
        ),

        Location(
            id: UUID(),
            name: "Noisy Miner",
            description: "An aggressive honey-eater that often dominates suburban trees.",
            latitude: -27.5378,
            longitude: 152.9782,
            visited: 0,
            quizQuestion: "Why are Noisy Miners often disliked?",
            quizAnswers: ["They steal food", "They swoop", "They displace other birds", "They carry disease"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .animal,
            zone: "Oxley"
        ),

        Location(
            id: UUID(),
            name: "Blue-tongue Lizard",
            description: "Large skink known for its blue tongue used to scare predators.",
            latitude: -27.4270,
            longitude: 153.0620,
            visited: 0,
            quizQuestion: "What does the Blue-tongue Lizard do when threatened?",
            quizAnswers: ["Plays dead", "Bites", "Runs fast", "Shows its blue tongue"],
            correctAnswerIndex: 3,
            quizCompleted: false,
            category: .animal,
            zone: "Nundah"
        ),

        Location(
            id: UUID(),
            name: "Brisbane River Turtle",
            description: "A rare turtle found only in the Brisbane River system.",
            latitude: -27.4752,
            longitude: 153.0231,
            visited: 0,
            quizQuestion: "Where is the Brisbane River Turtle found?",
            quizAnswers: ["Australia-wide", "Only Brisbane River", "Queensland coast", "Great Barrier Reef"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .animal,
            zone: "Brisbane CBD"
        ),

        Location(
            id: UUID(),
            name: "Australian White Ibis",
            description: "Urban-adapted bird known as the 'bin chicken' for scavenging food.",
            latitude: -27.4688,
            longitude: 153.0250,
            visited: 0,
            quizQuestion: "Why is the Australian White Ibis called a 'bin chicken'?",
            quizAnswers: ["It nests in bins", "It’s covered in food", "It eats human rubbish", "It’s small and round"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .animal,
            zone: "Roma Street"
        ),

        Location(
            id: UUID(),
            name: "Green Tree Frog",
            description: "A common bright green frog known for loud croaking after rain.",
            latitude: -27.4955,
            longitude: 152.9783,
            visited: 0,
            quizQuestion: "When are Green Tree Frogs most vocal?",
            quizAnswers: ["During sunrise", "Before storms", "After rain", "At night"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .animal,
            zone: "Indooroopilly"
        ),

        Location(
            id: UUID(),
            name: "Swamp Wallaby",
            description: "A solitary wallaby species found in Brisbane's bushland edges.",
            latitude: -27.5221,
            longitude: 152.9431,
            visited: 0,
            quizQuestion: "What is a key feature of the Swamp Wallaby?",
            quizAnswers: ["Hops backward", "Lives in trees", "Dark fur and solitary", "Bright red fur"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .animal,
            zone: "Kenmore"
        ),

        Location(
            id: UUID(),
            name: "Powerful Owl",
            description: "Australia’s largest owl, occasionally spotted in Brisbane bushland.",
            latitude: -27.5061,
            longitude: 152.8872,
            visited: 0,
            quizQuestion: "What does the Powerful Owl primarily eat?",
            quizAnswers: ["Fruit", "Insects", "Small mammals", "Fish"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .animal,
            zone: "Brookfield"
        ),

        Location(
            id: UUID(),
            name: "Pied Butcherbird",
            description: "Melodic bird with black and white plumage.",
            latitude: -27.4364,
            longitude: 153.0552,
            visited: 0,
            quizQuestion: "What is the Pied Butcherbird best known for?",
            quizAnswers: ["Nesting in buildings", "Mimicking chainsaws", "Melodic singing", "Dancing"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .animal,
            zone: "Clayfield"
        ),

        Location(
            id: UUID(),
            name: "Eastern Curlew",
            description: "Migratory shorebird with a long, down-curved bill.",
            latitude: -27.4002,
            longitude: 153.0993,
            visited: 0,
            quizQuestion: "Where does the Eastern Curlew migrate from?",
            quizAnswers: ["Africa", "South America", "Asia", "Antarctica"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .animal,
            zone: "Wynnum"
        ),

        Location(
            id: UUID(),
            name: "Golden Orb Weaver Spider",
            description: "Spider known for its massive golden webs in Brisbane parks.",
            latitude: -27.4654,
            longitude: 153.0310,
            visited: 0,
            quizQuestion: "What is unique about the Golden Orb Weaver’s web?",
            quizAnswers: ["Glows blue", "Smells sweet", "Is golden-colored", "Stretches for meters"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .animal,
            zone: "Spring Hill"
        ),

        Location(
            id: UUID(),
            name: "Australian Wood Duck",
            description: "Common duck seen foraging in grassy parks and wetlands.",
            latitude: -27.4673,
            longitude: 153.0444,
            visited: 0,
            quizQuestion: "What do Australian Wood Ducks mainly eat?",
            quizAnswers: ["Insects", "Fish", "Grass", "Berries"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .animal,
            zone: "Norman Park"
        ),

        Location(
            id: UUID(),
            name: "Carpet Python",
            description: "Non-venomous snake often found in Brisbane sheds and roofs.",
            latitude: -27.4756,
            longitude: 153.0557,
            visited: 0,
            quizQuestion: "Is the Carpet Python venomous?",
            quizAnswers: ["Yes", "No", "Only as a baby", "Only at night"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .animal,
            zone: "Coorparoo"
        ),

        Location(
            id: UUID(),
            name: "Flying Fox",
            description: "Large bat that helps pollinate native trees.",
            latitude: -27.4862,
            longitude: 153.0088,
            visited: 0,
            quizQuestion: "Why are flying foxes important to ecosystems?",
            quizAnswers: ["They eat pests", "They fertilize soil", "They pollinate flowers", "They make nests"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .animal,
            zone: "Auchenflower"
        ),

        Location(
            id: UUID(),
            name: "Bush Stone-curlew",
            description: "A ground-dwelling bird with haunting night calls.",
            latitude: -27.4587,
            longitude: 153.0268,
            visited: 0,
            quizQuestion: "What is unique about the Bush Stone-curlew?",
            quizAnswers: ["It walks on two legs", "It lives in water", "It has a haunting cry", "It glows in the dark"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .animal,
            zone: "West End"
        ),
        Location(
            id: UUID(),
            name: "Brisbane Wattle",
            description: "A native shrub with golden-yellow flowers, common in SEQ bushland.",
            latitude: -27.4701,
            longitude: 153.0215,
            visited: 0,
            quizQuestion: "What color are Brisbane Wattle flowers?",
            quizAnswers: ["Red", "Purple", "Yellow", "White"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .plant,
            zone: "Brisbane City"
        ),

        Location(
            id: UUID(),
            name: "Lilly Pilly",
            description: "Evergreen tree with edible pink berries and glossy leaves.",
            latitude: -27.4675,
            longitude: 153.0289,
            visited: 0,
            quizQuestion: "What part of the Lilly Pilly is edible?",
            quizAnswers: ["Leaves", "Roots", "Berries", "Bark"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .plant,
            zone: "Spring Hill"
        ),

        Location(
            id: UUID(),
            name: "Moreton Bay Fig",
            description: "Large tree with spreading roots often seen in Brisbane parks.",
            latitude: -27.4813,
            longitude: 153.0204,
            visited: 0,
            quizQuestion: "What is distinctive about the Moreton Bay Fig?",
            quizAnswers: ["It grows flowers", "It has aerial roots", "It’s small", "It’s only found on islands"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .plant,
            zone: "Petrie Terrace"
        ),

        Location(
            id: UUID(),
            name: "Grass Tree",
            description: "Slow-growing plant with a blackened trunk and tall flowering spike.",
            latitude: -27.4506,
            longitude: 153.0148,
            visited: 0,
            quizQuestion: "What is a unique feature of the Grass Tree?",
            quizAnswers: ["Smells like mint", "Grows fruit", "Has a tall spike", "Changes color every year"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .plant,
            zone: "Red Hill"
        ),

        Location(
            id: UUID(),
            name: "Bottlebrush",
            description: "A native shrub with red, brush-like flowers loved by birds.",
            latitude: -27.4902,
            longitude: 153.0315,
            visited: 0,
            quizQuestion: "Why is the Bottlebrush named so?",
            quizAnswers: ["Its fruit resembles a bottle", "Its leaves clean bottles", "Its flowers look like brushes", "It grows in bottles"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .plant,
            zone: "East Brisbane"
        ),

        Location(
            id: UUID(),
            name: "Blue Quandong",
            description: "Tall rainforest tree with bright blue fruits.",
            latitude: -27.4251,
            longitude: 153.0156,
            visited: 0,
            quizQuestion: "What color are Blue Quandong fruits?",
            quizAnswers: ["Green", "Blue", "Red", "Orange"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .plant,
            zone: "Ashgrove"
        ),

        Location(
            id: UUID(),
            name: "Kangaroo Grass",
            description: "Native grass important for erosion control and native animals.",
            latitude: -27.5124,
            longitude: 152.9963,
            visited: 0,
            quizQuestion: "What is Kangaroo Grass mainly used for?",
            quizAnswers: ["Medicine", "Erosion control", "Perfume", "Decoration"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .plant,
            zone: "Sherwood"
        ),

        Location(
            id: UUID(),
            name: "Native Violet",
            description: "Low-growing ground cover with delicate purple and white flowers.",
            latitude: -27.4431,
            longitude: 152.9777,
            visited: 0,
            quizQuestion: "Where does the Native Violet usually grow?",
            quizAnswers: ["In trees", "Underwater", "On rocks", "On the ground"],
            correctAnswerIndex: 3,
            quizCompleted: false,
            category: .plant,
            zone: "Bardon"
        ),

        Location(
            id: UUID(),
            name: "River Sheoak",
            description: "Fast-growing tree commonly seen along Brisbane waterways.",
            latitude: -27.4558,
            longitude: 153.0412,
            visited: 0,
            quizQuestion: "Where is the River Sheoak commonly found?",
            quizAnswers: ["Rainforests", "Deserts", "Riverbanks", "Mountains"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .plant,
            zone: "New Farm"
        ),

        Location(
            id: UUID(),
            name: "Native Hibiscus",
            description: "A shrub with large purple or pink flowers that bloom in summer.",
            latitude: -27.4791,
            longitude: 153.0074,
            visited: 0,
            quizQuestion: "When does the Native Hibiscus typically bloom?",
            quizAnswers: ["Winter", "Spring", "Summer", "Autumn"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .plant,
            zone: "Toowong"
        ),

        Location(
            id: UUID(),
            name: "Pale Headed Rosella Gum",
            description: "A native eucalypt important to birds and insects.",
            latitude: -27.5281,
            longitude: 152.9875,
            visited: 0,
            quizQuestion: "Why is this tree important?",
            quizAnswers: ["It produces nuts", "It supports wildlife", "It grows rapidly", "It repels pests"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .plant,
            zone: "Oxley"
        ),

        Location(
            id: UUID(),
            name: "Weeping Lilly Pilly",
            description: "Tree with glossy leaves, white flowers, and red fruit.",
            latitude: -27.4945,
            longitude: 153.0601,
            visited: 0,
            quizQuestion: "What does the Weeping Lilly Pilly produce?",
            quizAnswers: ["Thorns", "Red fruit", "Sticky leaves", "Purple flowers"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .plant,
            zone: "Cannon Hill"
        ),

        Location(
            id: UUID(),
            name: "Paperbark Tree",
            description: "Tree with thick, spongy bark and white bottlebrush-like flowers.",
            latitude: -27.4476,
            longitude: 152.9360,
            visited: 0,
            quizQuestion: "What is unique about the Paperbark Tree?",
            quizAnswers: ["Its flowers smell like smoke", "It has paper-like bark", "It grows upside down", "It glows at night"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .plant,
            zone: "Kenmore"
        ),

        Location(
            id: UUID(),
            name: "Black Bean Tree",
            description: "Large native tree with decorative seed pods.",
            latitude: -27.4342,
            longitude: 152.9178,
            visited: 0,
            quizQuestion: "What is a feature of the Black Bean Tree?",
            quizAnswers: ["Blue flowers", "Edible leaves", "Large seed pods", "Fuzzy trunk"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .plant,
            zone: "Brookfield"
        ),

        Location(
            id: UUID(),
            name: "Native Rosemary",
            description: "Shrub with scented leaves and tiny purple flowers.",
            latitude: -27.4090,
            longitude: 153.0322,
            visited: 0,
            quizQuestion: "What scent does Native Rosemary have?",
            quizAnswers: ["Pepper", "Rose", "Eucalyptus", "Spicy herb"],
            correctAnswerIndex: 3,
            quizCompleted: false,
            category: .plant,
            zone: "Wilston"
        ),

        Location(
            id: UUID(),
            name: "Forest Red Gum",
            description: "A tall eucalypt with smooth bark and a key koala food source.",
            latitude: -27.4921,
            longitude: 153.0383,
            visited: 0,
            quizQuestion: "Which animal relies on Forest Red Gum leaves?",
            quizAnswers: ["Possum", "Koala", "Wallaby", "Cockatoo"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .plant,
            zone: "Highgate Hill"
        ),

        Location(
            id: UUID(),
            name: "Native Frangipani",
            description: "Tree with fragrant yellow and white flowers, unrelated to exotic frangipani.",
            latitude: -27.4227,
            longitude: 152.9980,
            visited: 0,
            quizQuestion: "What makes Native Frangipani distinct?",
            quizAnswers: ["It's not fragrant", "It’s a vine", "It’s not related to exotic frangipani", "It grows in water"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .plant,
            zone: "The Gap"
        ),

        Location(
            id: UUID(),
            name: "Wattle Mat-Rush",
            description: "Tough groundcover plant that forms dense mats and yellow flower spikes.",
            latitude: -27.4625,
            longitude: 153.0466,
            visited: 0,
            quizQuestion: "What is the Wattle Mat-Rush useful for?",
            quizAnswers: ["Fuel", "Covering ground", "Growing fruit", "Flower arrangements"],
            correctAnswerIndex: 1,
            quizCompleted: false,
            category: .plant,
            zone: "Hawthorne"
        ),

        Location(
            id: UUID(),
            name: "Red Bottlebrush",
            description: "Another species of bottlebrush with bright red flowers and needle-like leaves.",
            latitude: -27.5094,
            longitude: 153.0275,
            visited: 0,
            quizQuestion: "What wildlife does Red Bottlebrush attract?",
            quizAnswers: ["Fish", "Lizards", "Birds and bees", "Frogs"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .plant,
            zone: "Annerley"
        ),

        Location(
            id: UUID(),
            name: "Native Ginger",
            description: "Rainforest plant with large leaves and edible rhizomes.",
            latitude: -27.5202,
            longitude: 152.9841,
            visited: 0,
            quizQuestion: "What part of Native Ginger is edible?",
            quizAnswers: ["Leaves", "Seeds", "Roots", "Flowers"],
            correctAnswerIndex: 2,
            quizCompleted: false,
            category: .plant,
            zone: "Graceville"
        )





        
        

        
        
    
        
        
        
        

    ]

    // Some of this code was taken from (https://forums.swift.org/t/json-decoding-failing-for-only-one-field/68596) and (https://developer.apple.com/documentation/foundation/jsonencoder) and the playlist (https://www.youtube.com/watch?v=9xzHJAT_Iqk&list=PLBn01m5Vbs4A0dus7gfymgj0UI1qKTe3M)
    // Tries to load a bunch of locations using JSON decoder
    static func loadLocations() -> [Location] {
        guard let url = getFileURL() else { return defaultLocations }

        do {
            let data = try Data(contentsOf: url)
            let decoder = JSONDecoder()
            var savedLocations = try decoder.decode([Location].self, from: data)

            // If this is the first launch and there are no saved locations,
            // initialize with the defaults and save them.
            if savedLocations.isEmpty {
                saveLocations(defaultLocations)
                return defaultLocations
            }

            return savedLocations
        } catch {
            print("Error loading locations: \(error)")
            // On error (e.g., corrupt file), return defaults and overwrite file
            saveLocations(defaultLocations)
            return defaultLocations
        }
    }

    // Call when any changes are made to save the changes on the file
    static func saveLocations(_ locations: [Location]) {
        guard let url = getFileURL() else { return }

        do {
            let encoder = JSONEncoder()
            let data = try encoder.encode(locations)
            try data.write(to: url)
        } catch {
            print("Failed to save locations: \(error)")
        }
    }

    //gets the position of the file in the iPhone
    static private func getFileURL() -> URL? {
        let fileManager = FileManager.default
        let directory = fileManager.urls(
            for: .documentDirectory,
            in: .userDomainMask
        ).first
        return directory?.appendingPathComponent(fileName)
    }
}
